CREATE TABLE cliente (
id SERIAL NOT NULL,
rut VARCHAR(20) NOT NULL, 
nombre VARCHAR(25) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(12) NOT NULL, 
direccion VARCHAR(255) NOT NULL, 
telefono VARCHAR(15) NOT NULL,
PRIMARY KEY(rut));